---
 
- hosts: OP
  gather_facts: no
  
  pre_tasks:

   - name: Instalar Python
     raw: sudo apt-get -y install python-simplejson

  tasks:

   - name: Instalar Git 
     become: true
     apt: pkg=git state=installed update_cache=true 
     notify: Start git

   - name: Creación de usuario "git" local
     user:
      name: git
      password: "{{ 'git' | password_hash('sha512') }}"
      groups: git
      update_password: on_create
      state: present
      shell: /bin/bash
      home: /home/proyecto

   - name: Creación directorio git 
     become: true
     file: path=/home/proyecto state=directory owner=git group=git mode=0775
     
   - name: Copiar clave privada
     copy: src=claves/id_rsa.pub dest=/home/proyecto/.ssh/ owner=git group=git mode=0600

   - name: Copiar clave pública
     copy: src=claves/id_rsa dest=/home/proyecto/.ssh/ owner=git group=git mode=0600

   - name: Clonación del repositorio
     git: repo=git@github.com:Kirissuno/Bangkok.git dest=/home/proyecto/Bangkok key_file=/home/proyecto/.ssh/id_rsa accept_hostkey=yes force=yes
     
   - name: Iniciando git en el repositorio clonado
     shell: /usr/bin/git init /home/proyecto/Bangkok

   - name: Cambiando propietario de la carpeta
     file:
       path: /home/proyecto/Bangkok
       owner: git
       group: git
       mode: 0755
       recurse: yes 
     
  handlers:
 
    - name: Start git 
      service: name=git state=started
